### ISSUE TITLE
Installation validation: Error with report creation

### ISSUE THREAD

**Issue by biju-benjamin** [Open-Systems-Pharmacology/InstallationValidator#162]
The following is the output message with couple of preceding lines. I do not see a log file. Has it got to do with compilation of  report file?

Number of compared files: 125
Overall comparison result: Valid

Starting report creation...
```
Report could not be created. Please see log for details located under 
'\AppData\Roaming\Open Systems Pharmacology\InstallationValidator\7.3\Outputs\753e8d2b-d812-4560-95e5-1f5829498420' For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org). 

Stack trace:
 at OSPSuite.TeXReporting.ReportCompiler.d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 at OSPSuite.TeXReporting.ReportCreator.d__6`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 at OSPSuite.Infrastructure.Reporting.ReportingTask.d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 at InstallationValidator.Core.Services.ValidationReportingTask.d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
 at InstallationValidator.Core.Presentation.MainPresenter.d__11.MoveNext()
```

**Comment by msevestre** [comment]
@biju-benjamin 

>The following is the output message with couple of preceding lines. I do not see a log file. Has it got to do with compilation of report file?

yes absolutely.Validation worked on your machine. For some reason however , the PDF creation was not successful.

Can you verify that you can create a simple report from PKSIm (it's using the same engine). Simply start PKSim, crate an individual and right click on the indivudal to export it to PDF

If this work, I'd suggest to run the installation validator again


What system are you using?

**Comment by biju-benjamin** [comment]
Thanks for a quick response

 The PDF report is not getting created with a sample-individual. I am attaching the screenshot with the folder opened in background. I can see the .tex file. Looks like a problem with .tex  compilation to pdf.

Not sure if this is the right way however, opened the .tex files with Texworks and tried to compile to PDF, but it crashes (screenshot attached) with a compiler driver error. I am not sure if it was broken earlier. Would you recommend a re-installation of Mikitex.

My system is core I5 3rd gen 4gb RAM 64 bit  with win 10 Pro. I also have pandoc mikitex (was prior installed)  cygwin, Rtools gfortran.....

best

Biju

![pdf report creation error](https://user-images.githubusercontent.com/25569284/41708612-b1cee1a8-755e-11e8-96f1-164ffe26ea61.png)
![texworks error](https://user-images.githubusercontent.com/25569284/41708613-b2079034-755e-11e8-93d9-ca344185b40a.png)

**Comment by biju-benjamin** [comment]
Tried on a different system. problem repeats itself. 
Both systems had mikitex pre-installed. possible that it breaks the configuration of standalone mikitex coming with the OSP suite installer.
Running the standalone texworks inside OSP suite it gives a memory dump error (possibly due to existing installation configuration). 
Installed version of mikitex is works fine. In this case a compilation should have worked with the report tex files created by PK-sim. it fails due to lack of sty files. 
Problem to me looks to be with the currently available mikitex version 2.9.6753 and specifically with  package 'l3kernel'. Many styles are missing in the current package version from the repository in comparison to the one provided with the suite or probably they are custom.

Hope it helps bring a solution

best

B

**Comment by msevestre** [comment]
@biju-benjamin Thanks for your feedback

I have absolutely no experience with miktex whatsoever so I can only stipulate that the problem is indeed due to concurrent installation of miktex. 

>Installed version of mikitex is works fine. In this case a compilation should have worked with the report tex files created by PK-sim. it fails due to lack of sty files.
The suite comes with a bunch of styles out of the box? It this the one you are referring to?
https://github.com/Open-Systems-Pharmacology/OSPSuite.TeXReporting/blob/master/src/Templates/StandardTemplate/OSPSuite.sty

>Problem to me looks to be with the currently available mikitex version 2.9.6753 and specifically with package 'l3kernel'. Many styles are missing in the current package version from the repository in comparison to the one provided with the suite or probably they are custom.

No custom styles other than the one mentioned above. However the OSPSUite setup comes indeed with a bunch of preinstalled packages. This is maybe the issue that you have
Check it out here
https://github.com/Open-Systems-Pharmacology/MiKTeX

If you have any idea how to solve the issue, please let us know

**Comment by msevestre** [comment]
probably same as https://github.com/Open-Systems-Pharmacology/InstallationValidator/issues/180
